export const todayISO = () => new Date().toISOString().slice(0, 10);

export const defaultData = {
  profile: {
    name: "أمل محمود",
    age: "54",
    phone: "0100 000 0000",
    emergencyName: "مريم - ابنة المريضة",
    emergencyPhone: "0101 111 1111",
    doctor: "د. أحمد سالم",
    hospital: "مركز الشفاء للأورام",
    cancerType: "سرطان الثدي",
    treatmentType: "علاج كيميائي",
    allergies: "لا توجد حساسية مسجلة",
    notes: "يُفضل التواصل مع المرافق قبل أي تغيير في الموعد.",
    bloodType: "A+",
    planName: "خطة العلاج المساعدة",
  },
  cycles: [
    {
      id: "cycle-1",
      number: "الدورة الثالثة",
      start: "2026-06-01",
      end: "2026-06-21",
      treatmentFrom: "2026-06-01",
      treatmentTo: "2026-06-03",
      restFrom: "2026-06-04",
      restTo: "2026-06-21",
      location: "مركز الشفاء - الدور الثاني",
      sessionName: "جلسة العلاج حسب خطة الطبيب",
      doctorNotes: "عمل تحليل CBC قبل الدورة التالية.",
      status: "active",
      instructionIds: ["ins-1", "ins-3"],
    },
    {
      id: "cycle-2",
      number: "الدورة الرابعة",
      start: "2026-06-22",
      end: "2026-07-12",
      treatmentFrom: "2026-06-22",
      treatmentTo: "2026-06-24",
      restFrom: "2026-06-25",
      restTo: "2026-07-12",
      location: "مركز الشفاء - الدور الثاني",
      sessionName: "جلسة العلاج حسب خطة الطبيب",
      doctorNotes: "إحضار نتائج التحاليل مع قائمة الأعراض.",
      status: "upcoming",
      instructionIds: ["ins-1", "ins-2"],
    },
  ],
  appointments: [
    {
      id: "apt-1",
      title: "جلسة العلاج القادمة",
      type: "جرعة علاج",
      date: "2026-06-22",
      startTime: "11:00",
      endTime: "13:00",
      location: "مركز الشفاء للأورام",
      department: "وحدة العلاج",
      notes: "إحضار تحليل CBC.",
      reminder: "قبل الموعد بيوم",
    },
    {
      id: "apt-2",
      title: "كشف متابعة مع الطبيب",
      type: "كشف دكتور",
      date: "2026-06-18",
      startTime: "16:30",
      endTime: "17:00",
      location: "عيادة د. أحمد",
      department: "الأورام",
      notes: "مناقشة الأعراض المسجلة.",
      reminder: "قبل الموعد بساعتين",
    },
    {
      id: "apt-3",
      title: "تحليل CBC",
      type: "تحليل",
      date: "2026-06-20",
      startTime: "09:00",
      endTime: "09:30",
      location: "المعمل الرئيسي",
      department: "التحاليل",
      notes: "قبل الجلسة القادمة.",
      reminder: "قبل الموعد بيوم",
    },
  ],
  medications: [
    {
      id: "med-1",
      name: "دواء الغثيان",
      dose: "قرص بعد الأكل حسب تعليمات الطبيب",
      time: "20:00",
      frequency: "مرة يوميًا",
      start: "2026-06-01",
      end: "2026-06-10",
      notes: "لا تُكرر الجرعة عند النسيان إلا بعد سؤال الطبيب.",
      state: "pending",
    },
    {
      id: "med-2",
      name: "العلاج الداعم",
      dose: "حسب تعليمات الطبيب المكتوبة",
      time: "09:00",
      frequency: "مرة يوميًا",
      start: "2026-06-01",
      end: "2026-06-21",
      notes: "تناول الدواء في الموعد المحدد.",
      state: "taken",
    },
  ],
  symptoms: [
    {
      id: "sym-1",
      date: "2026-06-03",
      name: "إرهاق",
      severity: "4",
      temperature: "37.1",
      nausea: "خفيف",
      pain: "لا يوجد",
      fatigue: "متوسط",
      appetite: "أقل من المعتاد",
      sleep: "جيد",
      mood: "مستقر",
      bleeding: "لا",
      notes: "تحسن بعد الراحة.",
    },
    {
      id: "sym-2",
      date: "2026-06-02",
      name: "غثيان",
      severity: "3",
      temperature: "36.8",
      nausea: "خفيف",
      pain: "لا يوجد",
      fatigue: "خفيف",
      appetite: "متوسط",
      sleep: "جيد",
      mood: "مستقر",
      bleeding: "لا",
      notes: "تم إبلاغ المرافق.",
    },
  ],
  labs: [
    {
      id: "lab-1",
      name: "CBC",
      date: "2026-06-20",
      beforeSession: "الدورة الرابعة",
      status: "pending",
      attachment: "",
      notes: "إحضار نسخة ورقية إلى الجلسة.",
    },
    {
      id: "lab-2",
      name: "وظائف الكبد",
      date: "2026-05-30",
      beforeSession: "الدورة الثالثة",
      status: "reviewed",
      attachment: "نتيجة-وظائف-الكبد.pdf",
      notes: "راجعها الطبيب.",
    },
  ],
  instructions: [
    {
      id: "ins-1",
      title: "التحضير قبل الجلسة القادمة",
      category: "قبل جلسة العلاج",
      text: "عمل تحليل CBC وإحضار النتيجة قبل الجلسة القادمة.",
      transcription: "اعملوا صورة دم كاملة قبل الجرعة القادمة وأحضروا النتيجة.",
      cycleId: "cycle-2",
      medicationId: "",
      appointmentId: "apt-1",
      instructionDate: "2026-06-03",
      doctor: "د. أحمد سالم",
      priority: "عاجل",
      caregiverNotes: "حجز التحليل يوم 20 يونيو.",
      attachment: "تسجيل-تعليمات-الجلسة.m4a",
      updatedAt: "2026-06-03",
      pinned: true,
      confirmed: true,
    },
    {
      id: "ins-2",
      title: "دواء الغثيان بعد الأكل",
      category: "الأدوية",
      text: "أخذ دواء الغثيان بعد الأكل وفي التوقيت الذي حدده الطبيب.",
      transcription: "",
      cycleId: "",
      medicationId: "med-1",
      appointmentId: "",
      instructionDate: "2026-06-01",
      doctor: "د. أحمد سالم",
      priority: "مهم",
      caregiverNotes: "تذكير الساعة الثامنة مساءً.",
      attachment: "",
      updatedAt: "2026-06-02",
      pinned: true,
      confirmed: true,
    },
    {
      id: "ins-3",
      title: "المياه خلال فترة الراحة",
      category: "فترة الراحة",
      text: "شرب كمية مناسبة من المياه حسب تعليمات الطبيب والحالة الصحية.",
      transcription: "",
      cycleId: "cycle-1",
      medicationId: "",
      appointmentId: "",
      instructionDate: "2026-06-03",
      doctor: "د. أحمد سالم",
      priority: "عادي",
      caregiverNotes: "",
      attachment: "",
      updatedAt: "2026-06-03",
      pinned: false,
      confirmed: true,
    },
  ],
  doctorNotes: [
    { id: "note-1", text: "هل نحتاج تعديل الطعام خلال فترة الراحة؟", done: false },
    { id: "note-2", text: "مراجعة مستوى الإرهاق في الزيارة القادمة.", done: true },
  ],
  emergencyItems: [
    "حرارة مرتفعة حسب الحد الذي حدده الطبيب",
    "نزيف أو ضيق تنفس",
    "قيء مستمر أو ألم شديد",
    "تدهور مفاجئ في الحالة",
  ],
  settings: {
    reminders: true,
    darkMode: false,
    language: "العربية",
  },
};

export const instructionCategories = [
  "الكل",
  "قبل جلسة العلاج",
  "يوم جلسة العلاج",
  "بعد جلسة العلاج",
  "فترة الراحة",
  "الأكل والشرب",
  "الأدوية",
  "التحاليل والأشعة",
  "الأعراض الجانبية",
  "النظافة وتقليل العدوى",
  "الحركة والراحة",
  "متى نتصل بالطبيب؟",
  "ممنوعات أو تحذيرات",
  "تعليمات خاصة من الدكتور",
];

export const statusLabels = {
  active: "نشطة",
  upcoming: "قادمة",
  completed: "مكتملة",
  delayed: "مؤجلة",
  pending: "قيد الانتظار",
  done: "تم",
  reviewed: "راجعها الطبيب",
  taken: "تم أخذه",
  missed: "فات الموعد",
};

export const formatDate = (date) => {
  if (!date) return "غير محدد";
  return new Intl.DateTimeFormat("ar-EG", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date(`${date}T12:00:00`));
};

export const formatShortDate = (date) => {
  if (!date) return "غير محدد";
  return new Intl.DateTimeFormat("ar-EG", {
    day: "numeric",
    month: "short",
  }).format(new Date(`${date}T12:00:00`));
};

export const formatTime = (time) => {
  if (!time || !/^\d{2}:\d{2}$/.test(time)) return "غير محدد";
  const [rawHour, minute] = time.split(":");
  const hour24 = Number(rawHour);
  const hour12 = hour24 % 12 || 12;
  const period = hour24 >= 12 ? "مساءً" : "صباحًا";
  return `${hour12}:${minute} ${period}`;
};
